# Site settings
title: FlyingSky
email: llmfei@gmail.com
author: Ramon Liu
description: "Every day work and thought"
baseurl: ""
url: "/"
google_analytics: 'UA-32555592-2'
animated: false
disqus_shortname: 'flyingsky'

# Enable future posts (this is to track a bug with --drafts causing issues)
future: true

# Build settings
markdown: kramdown
  
# Due to us using the categories for posts then it is advisable to explicitly specify a 
# permalink structure for the site. Otherwise Jekyll attempts to organize the pages in folders
# by the category names and it doesn't understand multi-categories to well :/
permalink: /:year/:month/:title.html

gems:
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  compressed: true

excerpt_separator: "\n\n"

# Pagination Settings
pagination:
  enabled: true
  per_page: 2
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
