# Site settings
title: FlyingSky
email: llmfei@gmail.com
author: Ramon Liu
description: "Every day work and thought"
baseurl: ""
url: "/"
google_analytics:
animated: false

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
sass:
  compressed: true

