# Site settings
title: FlyingSky
email: llmfei@gmail.com
author: Ramon Liu
description: "Every day work and thought"
baseurl: ""
url: "/"
google_analytics: 'UA-32555592-2'
animated: false
disqus_shortname: 'flyingsky'

# Build settings
markdown: kramdown
permalink: pretty
paginate: 10
sass:
  compressed: true

excerpt_separator: "\n\n"
